server:
  port: 8090

knife4j:
  enable: true
  openapi:
    title: VidWebSite后端接口文档

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vidwebsite
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    host: 192.168.10.134
    password: 123456

minio:
  endpoint: http://192.168.10.134:9000
  bucketName: video
  accessKey: PAP4PFSBE5342VZ3LK6L
  secretKey: qYDo9phhNJjpLlvZ02yuASv2+3W048VOslLIs8Zs

token:
  header: token
  expireTime: 30





